# Generated by Django 2.2.6 on 2020-06-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20200628_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='eu_sales',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='jp_sales',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='na_sales',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='year',
            field=models.IntegerField(),
        ),
    ]
