# Generated by Django 2.2.6 on 2020-07-25 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0003_auto_20200628_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_favorite',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
